name: tron4dummies

channels:
- conda-forge

dependencies:
  - python=3.7
  - numpy
  - scipy
  - scikit-learn
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - conda-forge::ipywebrtc
  
